{% set name = "jupyter-sshd-proxy" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_sshd_proxy-{{ version }}.tar.gz
  sha256: 2d4ea167f39864fd436173860798ebd1625385e248e070bf29c96354db34543b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - jupyter-server-proxy >=4.3.0
    - python >=3.8

test:
  imports:
    - jupyter_sshd_proxy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yuvipanda/jupyter-sshd-proxy
  summary: Run sshd under jupyter
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
    - yuvipanda
